firebase.apiKey=AIzaSyAcmPm7jzMuH2mNT7U2DYYQILDJKy23Big
firebase.projectId=myfinaces-c4860
google.oauthClientId=288237658868-anbqshh1m1fft87d9vdhudj4dcrcrg21.apps.googleusercontent.com
google.oauthClientSecret=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